use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Type of insight generated by the analysis engine
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InsightType {
    ThemeShift,
    SentimentChange,
    BeliefContradiction,
    NewPattern,
    MilestoneDetected,
}

/// An AI-generated observation about the user's data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Insight {
    pub id: String,
    pub insight_type: InsightType,
    pub title: String,
    pub body: String,
    pub time_range_start: Option<DateTime<Utc>>,
    pub time_range_end: Option<DateTime<Utc>>,
    pub supporting_evidence: Vec<String>,
    pub generated_at: DateTime<Utc>,
    pub prompt_version: Option<String>,
}
